### ISSUE TITLE
Support for new WebGPURenderer

### ISSUE THREAD

**Issue by Makio64** [protectwise/troika#338] opened 2024-11-07 08:20 UTC
WebGPURenderer in threejs use tsl/node system to be compatible with both webgl2 and webgpu.

In order to support WebGPURenderer and futur version of threejs part of the code have to been rewritten with the node/tsl system created by threejs team.

I would be interested if it's on the roadmap or off track ?

Thanks !

**Comment by lojjic** [comment] 2024-11-07 16:57
It's on the roadmap and I've played around with it a bit, but it's not a huge priority yet.

**Comment by lojjic** [comment] 2024-11-10 05:08
Duplicate of #264

**Closed by lojjic** 2024-11-10 05:08 UTC
